### ISSUE TITLE
Hardcoded cores

### ISSUE THREAD

**Issue by Andrej123456789** [StjepanBM1/i686-elf-build#1]
Example: https://github.com/StjepanBM1/i686-elf-build/blob/master/i686-elf-build.sh#L28

Please add numbers of cores as argument because user may want use more or less cores and it is faster than manually changing

**Comment by Andrej123456789** [comment]
You can for binutils and gcc version too

**Comment by StjepanBM1** [comment]
Wonderful idea! Will be added!

**Comment by Andrej123456789** [comment]
Great to hear
